language: python
dist: jammy
python:
  - '3.10'

env:
  - TOXENV=lint
  - TOXENV=tests
  - TOXENV=package

cache:
  pip: true

install:
  - python -m pip install --upgrade pip
  - python -m pip install tox

script:
  - tox -e $TOXENV
