version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Upgrade pip and install tox
          command: |
            python -m pip install --upgrade pip
            python -m pip install tox
      - run:
          name: Lint
          command: tox -e lint
      - run:
          name: Tests
          command: tox -e tests
      - run:
          name: Package
          command: tox -e package
workflows:
  version: 2
  build:
    jobs:
      - build
